name=OpenStreetMap-esp32
version=1.0.2
author=Cellie
maintainer=Cellie <CelliesProjects@users.noreply.github.com>
sentence=A library to display OpenStreetMap maps on ESP32 devices from SD card.
paragraph=This library allows you to display OpenStreetMap tiles on ESP32-based devices with a display. It supports reading tiles from SD card, caching, and zooming.
category=Display
url=https://github.com/CelliesProjects/OpenStreetMap-esp32
architectures=esp32
includes=OpenStreetMap-esp32.h
depends=LovyanGFX, PNGdec, SD, SPI
